import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'inbox2-loading-'));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(10000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
let mode='loading',reads=0;
const base={id:'gorgias:123',subject:'Order 10312345',customerName:'Example Customer',fromEmail:'person@example.com',status:'open',messages:[{id:'m',body:'Please check my order.',at:new Date().toISOString()}]};
const found={status:'found',customer:{displayName:'Example Customer',numberOfOrders:'4',amountSpent:{amount:'100.00',currencyCode:'USD'}},order:{id:'o',name:'#10312345',lineItems:{nodes:[]},shippingAddress:{address1:'Example address'}},history:[],returns:{returns:{nodes:[]}},fetchedAt:new Date().toISOString()};
await page.route('**/inbox/api/helpdesk',async route=>{
 const {tool}=route.request().postDataJSON();
 assert(['helpdesk.get_ticket','helpdesk.list_tickets','helpdesk.capabilities'].includes(tool));
 if(tool==='helpdesk.get_ticket')reads++;
 const rail=mode==='loading'?{status:'loading'}:mode==='found'?found:mode==='error'?{status:'error',refreshError:true}:mode==='missing'?{status:'missing'}:{status:'unavailable'};
 await route.fulfill({json:{ok:true,source:'gorgias_api',...(tool==='helpdesk.get_ticket'?{ticket:{...base,shopifyRail:rail}}:tool==='helpdesk.list_tickets'?{tickets:[base],total:1,nextOffset:null,projection:{complete:true}}:{})}});
});
await page.goto('http://127.0.0.1:8878/inbox/?ticket=gorgias%3A123');
await page.getByText('Loading Shopify customer details…').waitFor();
await page.locator('#reply').fill('Do not replace my reply');
mode='found';
await page.locator('.customer-stats').waitFor();
assert.equal(await page.locator('#reply').inputValue(),'Do not replace my reply');
assert(await page.locator('#reply').evaluate(el=>el===document.activeElement));
assert(reads>=2);
await page.screenshot({path:path.join(dir,'loaded.png')});
mode='error';await page.reload();await page.locator('[data-action="retry-customer"]').waitFor();
mode='found';await page.locator('[data-action="retry-customer"]').click();await page.locator('.customer-stats').waitFor();
mode='missing';await page.reload();await page.getByText('No matching Shopify customer was found.').waitFor();
mode='unavailable';await page.reload();await page.getByText('A consistent customer email is needed to look up Shopify details.').waitFor();
mode='loading';await page.setViewportSize({width:390,height:844});await page.reload();
await page.locator('.show-customer').click();
await page.locator('#customer-rail [data-action="rail-close"]').focus();
mode='found';await page.locator('.customer-stats').waitFor();
assert(await page.locator('#customer-rail [data-action="rail-close"]').evaluate(el=>el===document.activeElement));
await page.keyboard.press('Escape');
assert(await page.locator('.show-customer').evaluate(el=>el===document.activeElement));
assert.deepEqual(errors,[]);
await browser.close();
console.log('Passed: asynchronous details load, reply text/focus preservation, retry, missing/unavailable states, mobile drawer focus, no browser errors.');
