import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'inbox2-layout-'));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
page.setDefaultTimeout(10000);
const errors=[]; page.on('pageerror',error=>errors.push(error.message));
const now=new Date().toISOString();
const t={id:'gorgias:fixture',subject:'A long ticket subject about an order and return',customerName:'Example customer',fromEmail:'customer@example.com',status:'open',gorgiasPriority:'high',assigneeEmail:'support@example.com',channel:'email',updatedAt:now,syncedAt:now,readonlyDraft:'Hello,\n\nThank you for getting in touch. We will review your request.',draftAction:'sensitive_draft',draftReason:'Review the request before sending a response.',draftSourceMessageId:'fixture-message',draftProcessedAt:now,messages:[{id:'message',fromName:'Example customer',fromEmail:'customer@example.com',body:'Please review my order.\n\nhttps://example.com/order\n\nOn Monday someone wrote:\n> Earlier email history.',at:now}],shopifyRail:{status:'observed',customer:{displayName:'Example customer',numberOfOrders:12,amountSpent:{amount:'1240',currencyCode:'USD'}},order:{id:'order',name:'#12345',displayFinancialStatus:'PAID',displayFulfillmentStatus:'UNFULFILLED',currentTotalPriceSet:{shopMoney:{amount:100,currencyCode:'USD'}},fulfillments:[{displayStatus:'IN_PROGRESS',trackingInfo:[]}],lineItems:{nodes:[]}},returns:{returns:{nodes:[]}},history:[]}};
const calls=[];let mode='ok';
await page.route('**/inbox2/api/helpdesk',async route=>{
  const data=route.request().postDataJSON();calls.push(data);
  const name=data.tool.replace('helpdesk.','');
  assert(['capabilities','list_tickets','get_ticket','get_messages'].includes(name));
  if(mode==='error'&&name==='get_ticket')return route.fulfill({status:503,json:{message:'Temporarily unavailable'}});
  if(mode==='auth'&&name==='get_ticket')return route.fulfill({status:401,json:{}});
  await route.fulfill({json:{ok:true,source:'gorgias_api',...(name==='get_ticket'?{ticket:t}:name==='list_tickets'?{tickets:mode==='empty'?[]:[t],total:mode==='empty'?0:1,nextOffset:null,projection:{complete:true,generatedAt:now}}:{operatorEmail:'support@example.com'})}});
});
await page.goto('http://127.0.0.1:8878/inbox2/?ticket=gorgias%3Afixture');
await page.locator('.ticket-title').waitFor();
assert.equal(await page.locator('.status-control').evaluate(el=>getComputedStyle(el).color),'rgb(134, 80, 15)');
assert.equal(await page.locator('.order-statuses .badge').first().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(231, 242, 233)');
assert.equal(await page.locator('.order-statuses .badge').last().evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 241, 219)');
assert.equal(await page.locator('.shipment').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(255, 241, 219)');
await page.locator('[data-action="use-draft"]').click();
assert((await page.locator('#reply').inputValue()).startsWith('Hello,'));
await page.locator('#reply').fill('A local draft');
await page.locator('#details-tab').click();
assert.equal(await page.locator('#details-tab').getAttribute('aria-selected'),'true');
await page.keyboard.press('ArrowLeft');
assert.equal(await page.locator('#reply').inputValue(),'A local draft');
await page.locator('[data-view="open"]').click();
await page.waitForTimeout(100);
assert.equal(await page.locator('[data-view="open"]').getAttribute('aria-pressed'),'true');
await page.locator('#search').fill('return');
await page.waitForTimeout(400);
assert(calls.some(x=>x.tool==='helpdesk.list_tickets'&&x.arguments.query==='return'));
await page.locator('[data-action="rail-close"]').last().click();
assert(await page.locator('.rail-reopen').isVisible());
await page.locator('.rail-reopen .icon-button').click();
assert(await page.locator('#customer-rail').isVisible());
for(const width of [1920,1440,1230,1100,1041,1040,768,651,650,390,320]) {
  await page.setViewportSize({width,height:900});
  await page.waitForTimeout(30);
  const size=await page.evaluate(()=>({width:document.body.scrollWidth,height:document.body.scrollHeight,innerWidth,innerHeight}));
  assert(size.width<=size.innerWidth,`page overflow at ${width}: ${JSON.stringify(size)}`);
  assert(size.height<=size.innerHeight,`page scroll at ${width}: ${JSON.stringify(size)}`);
  if(width<=1040){
    await page.locator('.show-customer').click();
    assert.equal(await page.locator('#customer-rail').getAttribute('aria-modal'),'true');
    assert(await page.locator('#conversation').evaluate(el=>el.inert));
    await page.locator('#customer-rail [data-action="rail-close"]').focus();
    await page.keyboard.press('Shift+Tab');
    assert(await page.locator('#customer-rail').evaluate(el=>el.contains(document.activeElement)));
    await page.keyboard.press('Escape');
    assert(await page.locator('.show-customer').evaluate(el=>el===document.activeElement));
    assert.equal(await page.locator('.show-customer').getAttribute('aria-expanded'),'false');
  }
}
await page.screenshot({path:`${dir}/fixture-small.png`});
await page.setViewportSize({width:1440,height:1000});
await page.locator('#conversation').evaluate(el=>el.scrollTop=el.scrollHeight);
await page.screenshot({path:`${dir}/fixture-composer.png`});
await page.emulateMedia({reducedMotion:'reduce'});
assert.equal(await page.locator('.button').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
// Equivalent layout viewport to a 1280px window at 200% browser zoom.
await page.setViewportSize({width:640,height:450});
assert(await page.locator('.mobile-back').isVisible());
assert(await page.locator('#conversation').evaluate(el=>el.scrollHeight>el.clientHeight));
mode='error';await page.reload();await page.locator('.is-error').waitFor();
assert(await page.locator('[data-action="retry-ticket"]').isVisible());
mode='auth';await page.reload();await page.getByRole('heading',{name:'Sign in to continue'}).waitFor();
mode='empty';await page.goto('http://127.0.0.1:8878/inbox2/');await page.getByText('No tickets match this view.').waitFor();
assert.equal(errors.length,0,errors.join('\n'));
console.log('Passed: 11 viewport widths, independent scrolling, state colors, filters/search, local draft persistence, tabs/keyboard, rail collapse/drawer/focus, reduced motion, zoom layout, empty/error/auth states; zero browser errors.');
await browser.close();
