import assert from 'node:assert/strict';
import fs from 'node:fs';
const source=fs.readFileSync(new URL('../local_state.js',import.meta.url),'utf8');
const {stateRecords,readRecords,readState,localTicket,matchesLocal}=await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
assert.deepEqual(readRecords(['gorgias:1']),{});
assert.deepEqual(stateRecords({version:2,records:{unsafe:true}}),{});
assert.deepEqual(stateRecords({version:1,records:[]}),{});
const ticket={id:'gorgias:1',status:'open',gorgiasPriority:'normal',lastMessageAt:'2026-10-05T00:00:00Z',messages:[{id:'m1'}]};
const read={'gorgias:1':{read:true,message:'m1',activity:ticket.lastMessageAt}};
assert(readState(ticket,read));
assert(readState({id:ticket.id,lastMessageAt:ticket.lastMessageAt},read));
assert.equal(readState({...ticket,messages:[{id:'m2'}]},read),false);
assert.equal(readState({id:ticket.id,lastMessageAt:'2026-10-05T00:01:00Z'},read),false);
const effective=(t,f)=>f==='priority'?t.gorgiasPriority:t[f]||'';
assert.equal(matchesLocal({...ticket,spam:true},'all',{},effective,''),false);
assert(matchesLocal({...ticket,spam:true},'spam',{},effective,''));
assert(matchesLocal({...ticket,trashed:true},'trash',{},effective,''));
assert.equal(matchesLocal({...ticket,assigneeTeam:'Team'},'unassigned',{},effective,''),false);
assert.equal(matchesLocal(ticket,'assigned',{},effective,''),false);
assert(matchesLocal({...ticket,assignee:'owner@example.invalid'},'assigned',{},effective,'owner@example.invalid'));
assert.equal(matchesLocal({...ticket,snooze:'2026-10-06T00:00:00Z'},'snoozed',{},effective,'',Date.parse('2026-10-07T00:00:00Z')),false);
const local=localTicket({name:'Private customer',body:'A private message'},'uuid','2026-10-05T00:00:00Z');
assert.equal(local.id,'local:uuid');assert.equal(local.localOnly,true);assert.equal(local.fromEmail,'');assert.equal(local.messages[0].body,'A private message');
assert.throws(()=>localTicket({name:'',body:'Message'},'uuid'));
assert.throws(()=>localTicket({name:'Name',body:'x'.repeat(30001)},'uuid'));
console.log('Passed local record versions, read message watermarks, observed categories, assignment/snooze membership and validated private ticket shape.');
