"""Embed shared branding into standalone pages without new public asset routes."""
import argparse
import base64
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / "console-src/brand"
TARGETS = ("console-src/index.html", "console-src/login.html", "whatsapp-connect/server.js")
PATTERN = re.compile(r'<style id="buttonsbebe-brand">.*?</style>', re.DOTALL)


def data_uri(filename, mime):
    data = base64.b64encode((BRAND / filename).read_bytes()).decode("ascii")
    return f"data:{mime};base64,{data}"


def render():
    css = ["/* Generated by tools/sync_console_brand.py; edit console-src/brand instead. */"]
    for name, weight in (("Regular", 400), ("Medium", 500), ("SemiBold", 600)):
        uri = data_uri(f"Jost-{name}.ttf", "font/ttf")
        css.append(f'@font-face{{font-family:Jost;font-style:normal;font-weight:{weight};font-display:swap;src:url("{uri}") format("truetype")}}')
    logo = data_uri("logo.svg", "image/svg+xml")
    css.append(f':root{{--brand-logo:url("{logo}")}}')
    css.append((BRAND / "brand.css").read_text())
    result = '<style id="buttonsbebe-brand">\n' + "\n".join(css) + '</style>'
    # One target is a JS template literal. Keep generated content literal-safe.
    if "`" in result or "${" in result or "\\" in result:
        raise ValueError("Brand CSS must be safe inside a JavaScript template literal")
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    shared_block = render()
    stale = []
    for filename in TARGETS:
        block = shared_block
        path = ROOT / filename
        source = path.read_text()
        if len(PATTERN.findall(source)) > 1:
            raise ValueError(f"Duplicate brand blocks: {filename}")
        if PATTERN.search(source):
            updated = PATTERN.sub(lambda _: block, source)
        else:
            if source.count("</head>") != 1:
                raise ValueError(f"Expected one head: {filename}")
            updated = source.replace("</head>", block + "\n</head>")
        if updated != source:
            stale.append(filename)
            if not args.check:
                path.write_text(updated)
    if args.check and stale:
        parser.exit(1, "Run python3 tools/sync_console_brand.py: " + ", ".join(stale) + "\n")
    print("Brand embeds verified" if args.check else "Brand embeds updated")


if __name__ == "__main__":
    main()
